### ISSUE TITLE
Cannot compile with rustc 1.0.0

### ISSUE THREAD

**Issue by seprich** [alexcrichton/toml-rs#60]
Got following traceback:
```
$ cargo build --verbose
   Compiling toml v0.1.20
     Running `rustc /home/seprich/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-0.1.20/src/lib.rs --crate-name toml --crate-type lib -g -C metadata=e4d393d734aaa578 -C extra-filename=-e4d393d734aaa578 --out-dir /home/seprich/rust/manadochess/target/debug/deps --emit=dep-info,link -L dependency=/home/seprich/rust/manadochess/target/debug/deps -L dependency=/home/seprich/rust/manadochess/target/debug/deps --extern rustc_serialize=/home/seprich/rust/manadochess/target/debug/deps/librustc_serialize-2f8fcd98dcac2934.rlib -Awarnings`
       Fresh rustc-serialize v0.3.10
/home/seprich/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-0.1.20/src/parser.rs:394:27: 394:46 error: type `u32` does not implement any method in scope named `from_str_radix`
/home/seprich/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-0.1.20/src/parser.rs:394                     match u32::from_str_radix(num, 16).ok() {
                                                                                                                      ^~~~~~~~~~~~~~~~~~~
/home/seprich/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-0.1.20/src/parser.rs:394:46: 394:46 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/seprich/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-0.1.20/src/parser.rs:394:46: 394:46 help: candidate #1: use `core::num::FromStrRadix`
error: aborting due to previous error
Could not compile `toml`.

Caused by:
  Process didn't exit successfully: `rustc /home/seprich/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-0.1.20/src/lib.rs --crate-name toml --crate-type lib -g -C metadata=e4d393d734aaa578 -C extra-filename=-e4d393d734aaa578 --out-dir /home/seprich/rust/manadochess/target/debug/deps --emit=dep-info,link -L dependency=/home/seprich/rust/manadochess/target/debug/deps -L dependency=/home/seprich/rust/manadochess/target/debug/deps --extern rustc_serialize=/home/seprich/rust/manadochess/target/debug/deps/librustc_serialize-2f8fcd98dcac2934.rlib -Awarnings` (exit code: 101)
```
my rustc version:
```
$ rustc --version
rustc 1.0.0-nightly (6cf3b0b74 2015-03-30) (built 2015-03-31)
```

It seems that `from_str_radix` has been deprecated: https://doc.rust-lang.org/core/num/fn.from_str_radix.html

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like you may need to update your rustc, however:

```
$ rustc -V                            
rustc 1.0.0-nightly (d754722a0 2015-03-31) (built 2015-04-01)
```

After that you should be good to go!
